### ISSUE TITLE
rectangularZone port_emb

### ISSUE THREAD

**Issue by icupeiro** [open-ideas/IDEAS#1032]
Rectangular zones have the option to include an embedded port in the floor. Shouldn't this feature be added for the ceiling?

**Comment by Mathadon** [comment]
I'd like to maintain the convention that templates can be used to add floors, but not ceilings. I .e. the ceiling should be configured using the floor of the zone above it, or using a separate boundary wall. @damienpicard what do you think?

**Comment by icupeiro** [comment]
@Mathadon we can keep the convention and add the option only for outer walls as an exception. Is that a possibility?

**Comment by damienpicard** [comment]
@Mathadon and @icupeiro my experience from the Ter Potterie model is that only having the floor in the zone model is clearer. Otherwise, the chance is very high that an inexperienced user would define the floor twice and try to couple them.

Furthermore, I have now added radiators, VAV, and embeddedPipe in the zone template of my branch. Adding yet another fluid port for the ceiling is cumbersome.

**Comment by icupeiro** [comment]
issued closed!
