### ISSUE TITLE
cannot run the ThreeWayValves.mo example

### ISSUE THREAD

**Issue by alexandrecuer** [open-ideas/IDEAS#1140]
Hello,

Trying to run with openmodelica  the ThreeWayValves.mo example of the IDEAS library

https://github.com/open-ideas/IDEAS/blob/8fd99555d882cccf78f269f63b95d3f1f6dece0d/IDEAS/Fluid/Actuators/Valves/Examples/ThreeWayValves.mo#L1

got the following error : 
```
/tmp/OpenModelica_alexandrecuer/OMEdit/IDEAS.Fluid.Actuators.Valves.Examples.ThreeWayValves/IDEAS.Fluid.Actuators.Valves.Examples.ThreeWayValves -port=42463 -logFormat=xmltcp -override=startTime=0,stopTime=100,stepSize=0.2,tolerance=1e-6,solver=dassl,outputFormat=mat,variableFilter=.* -r=/tmp/OpenModelica_alexandrecuer/OMEdit/IDEAS.Fluid.Actuators.Valves.Examples.ThreeWayValves/IDEAS.Fluid.Actuators.Valves.Examples.ThreeWayValves_res.mat -w -lv=LOG_STATS -inputPath=/tmp/OpenModelica_alexandrecuer/OMEdit/IDEAS.Fluid.Actuators.Valves.Examples.ThreeWayValves -outputPath=/tmp/OpenModelica_alexandrecuer/OMEdit/IDEAS.Fluid.Actuators.Valves.Examples.ThreeWayValves
Solving non-linear system 82 failed at time=0.
For more information please use -lv LOG_NLS.
simulation terminated by an assertion at initialization
Simulation process failed. Exited with code 255.
Jacobian determinant is NaN.
Jacobian determinant is NaN.
Jacobian determinant is NaN.
Jacobian determinant is NaN.
Jacobian determinant is NaN.
Jacobian determinant is NaN.
nonlinear system 82 fails: at t=0
proper start-values for some of the following iteration variables might help
[1] Real valEquPerLin.res3.m_flow(start=0, nominal=1)
```
I've seen IDEAS was not designed to work with openmodelica...

maybe that's the reason ?

best

Alex

**Comment by Mathadon** [comment]
@alexandrecuer IDEAS is implemented in Modelica and OpenModelica is designed to support Modelica, so in theory there is no problem. However, OpenModelica does not support the full Modelica specification (and IDEAS sometimes unintentionally does not comply with the Modelica specification). We do not actively check compliance between IDEAS and OM so it can happen that things don't work as expected.

Now related to your problem: it seems that the Newton solver crashes on an algebraic loop. As far as I can tell this is something that has to be fixed in OpenModelica since these models work fine with Dymola.
