### ISSUE TITLE
Error in Buildings class declaration

### ISSUE THREAD

**Issue by rubenbaetens** [open-ideas/IDEAS#116]
```
When looking for class Buildings
 found directory E:/3_PhD/3_Modelica/issue51_BESTEST/IDEAS/Buildings,
 which is a part of a package.
 Please ensure that the MODELICAPATH does not contain directories inside packages
 and that the current directory is not inside a package.

 When looking for class Buildings
 found directory E:/3_PhD/3_Modelica/issue51_BESTEST/IDEAS/Buildings,
 which is a part of a package.
 Please ensure that the MODELICAPATH does not contain directories inside packages
 and that the current directory is not inside a package.
```

**Comment by phaabe** [comment]
@Mathadon could you publish the solution here? I am have the same issue right now.

**Comment by Mathadon** [comment]
What error do you get exactly and what folders are on your MODELICAPATH?

**Comment by phaabe** [comment]
The same as up there but with another path. I cannot copy you the error. I deleted the branch where the error occured. But if you can explain how this issue can be tackled when it occurs, this might be helpful in the future. 

I don't know what I did to get this error.

**Comment by Mathadon** [comment]
Well the problem is essentially that there exists a package `IDEAS.Buildings` and the library `Buildings` and Dymola could mix those two up if your MODELICAPATH is incurrect. Essentially your MODELICAPATH should contain folders that contain package.mo files where the folder name is the same as the library name of the package.mo file. If you do that correctly then it works for me!
