### ISSUE TITLE
larger than unity view factor

### ISSUE THREAD

**Issue by Mathadon** [open-ideas/IDEAS#1272]
Simple geometries can lead to larger than unity view factors. The existing assert should be extended to guard against this.

**Comment by Mathadon** [comment]
Use `(max(F1)<FMax*0.9 and computeCarroll) or (not computeCarroll and max(F2)<=1) or simVieFac`

**Comment by jelgerjansen** [comment]
@Mathadon is there a reason why this wasn't implemented back in the days?

**Comment by Mathadon** [comment]
Probably the extra hassle for running unit tests to make sure that I do not break some examples by implementing this fix.

**Comment by Mathadon** [comment]
> But if your added condition triggers this (not computeCarroll and max(F2)<=1), you cannot get rid of the warning by setting simVieFac=true.
I'm not sure what you mean exactly. If you add 'or true' to any boolean condition, the condition becomes true so the assert cannot trigger and hence you do get rid of the warning.

I would not add an assert but rather modify the existing assert to the version in my post of 19 may. An alternative would be to add an assert that checks `max(A)<sum(A)/2` since this seems to be the only way that `max(F2)>1` for `F2= A ./ (ones(nSurf)*sum(A) - A)`. The assert can then mention that the geometry is non-physical.

Throwing an error is perhaps a good idea since larger than unity view factors may violate the second law of thermodynamics, since other view factors become negative.

**Comment by jelgerjansen** [comment]
@Mathadon I meant that if for example `simVieFac=False`, `computeCarroll=False` (due to `max(A)>=sum(A)/2`), and `max(F2)>1`, setting `simVieFac=True` ensures that you get rid of the error, but this change will not affect the calculation of `F2` and therefore not solve the actual problem you want to guard against, being larger than unity view factors. So what is the added value of the modified assert in that case? Or do I still miss something?

The alternative formulation makes more sense to me, because than you indeed guard against the larger than unity view factor and force the user to reevaluate their building geometry. But in the alternative formulation we don't need to update the existing assert, do we?

**Comment by Mathadon** [comment]
> @Mathadon I meant that if for example `simVieFac=False`, `computeCarroll=False` (due to `max(A)>=sum(A)/2`), and `max(F2)>1`, setting `simVieFac=True` ensures that you get rid of the error, but this change will not affect the calculation of `F2` and therefore not solve the actual problem you want to guard against, being larger than unity view factors. So what is the added value of the modified assert in that case? Or do I still miss something?
No indeed, you are right! I would drop the`'or simVieFac` then in the assert and replace the error message with something relating to the non-physical parameters.
> 
> The alternative formulation makes more sense to me, because than you indeed guard against the larger than unity view factor and force the user to reevaluate their building geometry. But in the alternative formulation we don't need to update the existing assert, do we?

I guess there are different ways of dealing with it but my first guess would be to update the existing assert as explained above :)

**Comment by jelgerjansen** [comment]
Closed by #1359
