### ISSUE TITLE
Uniform emission parametrization

### ISSUE THREAD

**Issue by rubenbaetens** [open-ideas/IDEAS#223]
Could / Should we uniformise the parametrization of all emission coefficients ? Current implementation ```Fluid.HeatExchangers.Radiators.RadiatorEn442_2``` contains parameters for the nominal heating power and inlet / outlet temperatures, allowing a default m_flow_nominal. These parameters are, however, missing in ```Fluid.HeatExchangers.RadiantSlab.EmbeddedPipe``` making m_fow_nominal unknown. 

I propose to adopt the missing nominal parameters in the embedded pipe model (?).

**Comment by Mathadon** [comment]
I don't agree to adding three new parameters just to be able to calculate a nominal mass flow rate. This is too cumbersome for the user. Why would you like to make this change?

**Comment by rubenbaetens** [comment]
In order to do parametric runs changing the heating system, it is very cumbersome to have a lot of different parameters for similar models like e.g. emission components. While all emission components have nominal powers, nominal inlet temperatures, nominal outlet temperatures and nominal mass flows, it feels like a bug to define the first 3 in one model and deduce the 4th one for radiators while you have to enter the 4the one yourself by hand based on the others you used to design it.

**Comment by Mathadon** [comment]
I see, sounds reasonable.:) However, in case of my application I do not have nominal power/temperature data so this change would be a bit annoying because I’d have to invent these values and/or reverse engineer them. Is there a way to avoid needing to fill in these new parameters in my model?
You could for instance make the parameters conditional based on a boolean or you could make a model in your own library that extends from EmbeddedPipe and adds these parameters?

**Comment by rubenbaetens** [comment]
If there are default values given for the nominal temperatures and power, and the nominal mass flow is not final, nothing changes, no ? Though, how can you design an emission system without nominal power and temepratures ?
