### ISSUE TITLE
allowFlowReversal in Zone.Infiltration

### ISSUE THREAD

**Issue by rubenbaetens** [open-ideas/IDEAS#418]
The parameter `allowFlowReversal` is not correctly propagated in `IDEAS.Buildings.Components.Zone.airLeakage` and thus always `false`. This may give an assert( ) error.

Additionally, it seems to me `Zone.airLeakage` is wrongly connected to the MixingVolume `Zone.vol`. The 4 ports for both airLeakage and the Interface are connected to `{vol[1],vol[2]}` instead of `{vol[1],vol[2],vol[3],vol[4]}`.

**Comment by Mathadon** [comment]
It should always be false since the flow does not reverse. This property can be exploited by the solver.

It should be connected like this:
      if allowFlowReversal then
  connect(airLeakage.port_a, vol.ports[4]) annotation (Line(
      points={{40,40},{-10,40}},
      color={0,127,255},
      smooth=Smooth.None));
  connect(airLeakage.port_b, vol.ports[3]) annotation (Line(
      points={{60,40},{70,40},{70,14},{-32,14},{-32,40},{-10,40}},
      color={0,127,255},
      smooth=Smooth.None));
      else
  connect(airLeakage.port_a, vol.ports[2]) annotation (Line(
      points={{40,40},{-10,40}},
      color={0,127,255},
      smooth=Smooth.None));
  connect(airLeakage.port_b, vol.ports[1]) annotation (Line(
      points={{60,40},{70,40},{70,14},{-32,14},{-32,40},{-10,40}},
      color={0,127,255},
      smooth=Smooth.None));
      end if;

This is more efficient when allowFlowReversal=false

**Comment by rubenbaetens** [comment]
That's how it is connected, but `if allowFlowReversal  = false`, it seems to give an `assert( )` error in the zone. Why not always connect it to `{3,4}` ?

**Comment by rubenbaetens** [comment]
@Mathadon 
```
if ( not airLeakage.pipe_HeatPort.vol.allowFLowReversal) then 
assert( airLeakage.pipe_HeatPort.vol.ports[1].m_flow > - airLeakage.pipe_HeatPort.vol.m_flow_small,
"model has flow reversal, but the parameter allowFlowReversal is set to false. " )
```
