### ISSUE TITLE
Solar screen

### ISSUE THREAD

**Issue by rubenbaetens** [open-ideas/IDEAS#425]
The current solar screen model only corrects the solar irradiation for the known transmission `shaCorr`. In reality, these screens have a high relative absoprtion, and we could (should) correct the radiative heat transfer of the window based on the presence of the screen.

**Comment by Mathadon** [comment]
Do you have an implementation for this?

**Comment by rubenbaetens** [comment]
Not yet, i wrote it here as a "to keep in mind if i once have a bit of time"

**Comment by Mathadon** [comment]
We can implement this by passing `Tenv` through the shading model. Will propose an implementation for this.

**Comment by Mathadon** [comment]
I tested the significance of this by setting `TenvWindow = Tenv  + iSolDir/100`. This essentially increases the radiative heat exchange temperature of the environment for windows by 10K when the solar irradiation is 1000W/m2. This only affects the results slightly (<0.1K for `struct.TSensor[1]` in IDEAS.Examples.TwinHouses.BuildingN2_Exp1).

Implementing this properly would require the LW radiative heat exchange and convective heat exchange models to be changed and reproduced in the shading model. This is quite cumbersome and since the gained accuracy is small, I prefer to focus effort elsewhere.
