### ISSUE TITLE
Rename TStar into TRad

### ISSUE THREAD

**Issue by Mathadon** [open-ideas/IDEAS#551]
The zone model currently has a variable `TStar` that equals the radiative temperature of the zone, as computed (by default) using the star network approach. This is however not always the case (i.e. view factors may be used). Therefore I suggest to rename `TStar` into `TRad` such that the name better describes the variable. 
@rubenbaetens is this a problem?

**Comment by rubenbaetens** [comment]
From a building physics perspective, their is a clear distinction between `TStar` and `TRad`, that is: `TRad` is always the weighted mean surface temperature of zone, while `TStar` is the star node temperature of zone which in fact is the fourth square of the weighted mean of the fourth power of the surface temperature.

If you stick to those definitions, it is perfect.

**Comment by Mathadon** [comment]
I agree, but the point is that (I think) we're not sticking to those definitions :) When using the view factor implementation we still compute TStar, while it should be Trad since it is more general?

**Comment by rubenbaetens** [comment]
If the viewfactor implementation differs, it means you didn't stick to the definition ;-) it only matters for the calculation of the operative temperature, you need different weighting factors if you use `TRad` instead of `TStar` ... I suggest to always have a `TRad` in the model, and an additional `TStar` if the calculation method uses it for the radiative balance.

**Comment by Mathadon** [comment]
closed in #619
