### ISSUE TITLE
(un-)visible connectors

### ISSUE THREAD

**Issue by rubenbaetens** [open-ideas/IDEAS#555]
Many models have connectors which not always exist as defined by a boolean, e.g.
```
RealInput x if y;
```
in the solar shading or zone occupant model. However, even if `y = true` i notice the connector is often not visible and i'm wondering what's the exact correct notation here to (not) show it appropriately. Is there an `annotation(  )` that solves this ?

**Comment by Mathadon** [comment]
_In general_ the visibility only works when `y` can be evaluated directly, i.e. if it is an expression that does not refer to variables of other components. E.g. `y = boolParamA` works, but `y = someOtherCOmponent.boolParamB` does not work. In that latter case the symbol is shown. I do not know if there is an annotation to 'fix' this.

**Comment by rubenbaetens** [comment]
In the latter case the symbol is not shown it seems. Maybe it can be solved when redeclares are final ... ?

**Comment by Mathadon** [comment]
Maybe they changed it in Dymola 2017..

I think it's dymola that does not want to go through evaluating the model parameters on the fly while working in the GUI so I doubt that there's a lot the user can do except make a ticket for this.

We could work around the occupancy thing by also declaring a parameter for the occupancy and provide the boolean _option_ to input the occupancy using a `RealInput`. So then whether or not the input is activated depends on the boolean parameter instead of on the `intGai` redeclare. This would however allow to define an occupancy profile when not having an occupancy model, which would be confusing. So I'm not really in favour of that.

What may work is to add a new parameter `showSymbol` and set

```
Modelica.Blocks.Interfaces.RealInput nOcc if showSymbol or intGai.requireInput
```

if Dymola recognises that if `showSymbol==true`, then the entire expression is true, it should show the symbol.

**Comment by rubenbaetens** [comment]
I suggest to just close this issue, @Mathadon ?

**Comment by Mathadon** [comment]
One closed issue a day keeps the doctor away!

**Comment by lievehelsen** [comment]
You should have told me that before!
I’m too open ;-)

Best regards
Lieve
