### ISSUE TITLE
corrCV and energyDynamics in zone model

### ISSUE THREAD

**Issue by damienpicard** [open-ideas/IDEAS#570]
`IDEAS.Buildings.Components.ZoneAirModels.PartialAirModel` contains the parameters `mSenFac` and `energyDynamics` but this parameters are not propagated in the `zone` model. This is firstly not practical and secondly not backward compatible...

I propose to re-add them to the partial_zone model, except if they have been deleted for a particular reason? @Mathadon

**Comment by Mathadon** [comment]
The reason is that these parameters are part of an 'air model' and not part of a 'zone model'. For instance if you would choose a more complicated or simpler air model it may not make sense to have the parameter `mSenFac` or instead it should be `mSenFac[:]`. So I removed the parameter from the zone model to guard against future non-backward compatibilities. Similarly it does not make sense to have the parameter `energyDynamics` in the most simple air model implementation.
I agree that it is not practical though. 

Any other opinions/options?

**Comment by damienpicard** [comment]
What about propagating the parameters in the zone but make them conditional with a Boolean of the partialAirModel?

**Comment by Mathadon** [comment]
That would not work: enabling them conditionally in the Dialog annotation would not work because the boolean that determines the 'enable' flag is in a different model. So it would not be detected. Making the parameter itself conditional would not work because you cannot propagate it then into the `partialAirModel` since it can be conditionally removed.

**Comment by damienpicard** [comment]
I would propose to still propagate the parameters to the partial_zone as their are part of partialAirModel. We do not need to use them in the air model. We could add in the string documentation: only effective if air model is dynamic.

**Comment by rubenbaetens** [comment]
I would avoid having a parameter in a model that isn't used in certain conditions. That's very confusing for users. Hence i would only make the parameter in the dynamic model, not even in the partial. If the model is a replaceable, it's easy to find the parameters in the GUI.

**Comment by Mathadon** [comment]
@damienpicard is this fixed?
