### ISSUE TITLE
include final U value in construction interfaces

### ISSUE THREAD

**Issue by icupeiro** [open-ideas/IDEAS#794]
@damienpicard as discussed, for tuning/validation purposes, and like in the borefield model
include a boolean parameter in the construction interface such as use_U = true/false
if true, the model would use a given U parameter
if false, it will compute the U value as now

**Comment by damienpicard** [comment]
This could be a nice added value especially when the user can start from an EPB file. It might be useful to use that feature directly in the rectangularZoneModel and wall model (no need for construction then).

However, an additional parameter for light/medium/heavy construction also be added based on which the mass will be estimated.

**Comment by icupeiro** [comment]
hey @damienpicard 
I have been checking the model a little bit. At the very outer part you calculate a final parameter U_value, but it seems only for informative purposes. 
The real heat transfer occurs at the very inner part (monolayer dynamic and static models). The model goes layer by layer calculating the different heat fluxes. I guess that the change should be applied to the MultiLayer model, therefore you can use the U value (and estimated capacity) also in internalWalls, windows, etc... . I was thinking an if-statement, but wouldn't that create problems with linearizations and optimizations? Maybe a separate model with U_value and A as inputs?
Any insights on this?

**Comment by Mathadon** [comment]
I'm not sure what the idea is. You want to override the conductance of a `construction`? So not one layer, but the entire construction? And you intend to keep the thermal capacitance the same, or change that accordingly? For multiple layers you could compute a correction factor for the thermal conductances such that they add up to the requested U-value.. I think this should work for simple walls, but if you have cavities etc it may be trickier.

**Comment by damienpicard** [comment]
@Mathadon in my understanding it is the purpose to use a single U value and estimated capacitance instead of defining each layer. So a thick wall of a brick-insulation-concrete-plaster would simply be defined by a unique U-value and an estimation of the capacity based on a user-defined parameter light-medium-heavy, resulting in a single layer of a fictive material.

**Comment by icupeiro** [comment]
hey @Mathadon 
The idea is to give the user the option to use the Uvalue to define the Uvalue of a wall (indeed, the entire construction), so it can start from a EPB file as @damienpicard pointed. Also, it might be useful for model tuning purposes.
Regarding the capacitance, if no construction is used, it should be manually introduced by the user, e.g. as light/medium/heavy thermal mass

**Comment by Mathadon** [comment]
ah, make sense. But then I would make a new wall model for this with parameters `U` and `massiveness` (or similar), instead of adding options to the record? This better shows to the user that the model is fundamentally different, which is not clearly communicated when simply providing a boolean option in a record.

**Comment by Mathadon** [comment]
@icupeiro is there any progress on this?

**Comment by icupeiro** [comment]
@Mathadon low priority in my to-do list, but it will come...

**Comment by Mathadon** [comment]
Okay! I’ll leave it open then
