### ISSUE TITLE
Bug in bin/runUnitTests.py

### ISSUE THREAD

**Issue by bramvdh91** [open-ideas/IDEAS#835]
I tried to run part of the unit tests on my own computer in order to avoid having to wait for travis, but encountered following error:

```
C:\Users\u0094934\Documents\Dymola\IDEAS\IDEAS>python ..\bin\runUnitTests.py -s IDEAS.BoundaryConditions
Traceback (most recent call last):
  File "..\bin\runUnitTests.py", line 181, in <module>
    show_gui = args.show_gui)
  File "..\bin\runUnitTests.py", line 71, in _runUnitTests
    ut = u.Tester(tool=tool)
TypeError: __init__() got an unexpected keyword argument 'tool'
```
The argument `tool` is set default to `"dymola"`, but something seems to go wrong.

**Comment by Mathadon** [comment]
@bramvdh91 do you have an old version of buildingspy?

If you want to run the unit tests, it may be easier to use `IDEAS/RunUnitTests.py` instead of `bin/RunUnitTests.py`. The former one is used for travis, but is a bit more involved. Also, the tests have become a bit stricter so to avoid problems you should have dymola 2018FD01 and disable any startup script that you may have.

**Comment by Mathadon** [comment]
@bramvdh91 can this be closed?

**Comment by Mathadon** [comment]
@bramvdh91 can this be closed?

**Comment by bramvdh91** [comment]
Hi @Mathadon , I think it can be closed. I'm just wondering if results won't differ slightly depending on OS, and how this might affect developers who are not using Linux and want to add new reference results. For the rest, I guess Travis has got everything covered.

**Comment by Mathadon** [comment]
I don't think that the OS should matter a lot, but Dymola version makes a difference.
